[build]
  publish = "/"
  functions = "netlify/functions"

# Optional proxy if you ever want /api/* to map to functions on the Netlify site:
# [[redirects]]
#   from = "/api/*"
#   to   = "/.netlify/functions/:splat"
#   status = 200